// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6


using Store.Model.IdentityEntities;
using Store.Model.POCO_Entities;

#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Store.Model.POCO_Entities
{

    // Customer
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class Customer
    {
        public int CustomerId { get; set; } // CustomerId (Primary key)
        public string CustomerName { get; set; } // CustomerName (length: 30)
        public string CustomerEmail { get; set; } // CustomerEmail (length: 50)
        public string CustomerPatronymic { get; set; } // CustomerPatronymic (length: 40)
        public string CustomerLastName { get; set; } // CustomerLastName (length: 40)
        public string CustomerAddress { get; set; } // CustomerAddress (length: 50)
        public string CustomerCity { get; set; } // CustomerCity (length: 15)
        public string CustomerRegion { get; set; } // CustomerRegion (length: 20)
        public string CustomerCountry { get; set; } // CustomerCountry (length: 20)
        public int OrderCount { get; set; } // OrderCount
        public virtual ApplicationUser ApplicationUser { get; set; }

        // Reverse navigation

        /// <summary>
        /// Child CusomerPhones where [CusomerPhone].[CustomerId] point to this entity (Customer_CustomerPhone)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<CustomerPhone> CusomerPhones { get; set; } // CusomerPhone.Customer_CustomerPhone
        /// <summary>
        /// Child OrderProducts where [OrderProduct].[CustomerId] point to this entity (Customer_OrderProduct)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<OrderProduct> OrderProducts { get; set; } // OrderProduct.Customer_OrderProduct

        public Customer()
        {
            CusomerPhones = new System.Collections.Generic.List<CustomerPhone>();
            OrderProducts = new System.Collections.Generic.List<OrderProduct>();
        }
    }

}
// </auto-generated>
