// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6



#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Store.Model.POCO_Entities
{

    // OrderDetails
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class OrderDetail
    {
        public long OrderProductId { get; set; } // OrderProductId (Primary key)
        public int ProductId { get; set; } // ProductId (Primary key)
        public decimal OrderDetailsQuantity { get; set; } // OrderDetailsQuantity
        public decimal OrderDetailsPrice { get; set; } // OrderDetailsPrice
        public decimal? OrderDetailsDiscountPrice { get; set; } // OrderDetailsDiscountPrice

        // Foreign keys

        /// <summary>
        /// Parent OrderProduct pointed by [OrderDetails].([OrderProductId]) (OrderProduct_OrderDetails)
        /// </summary>
        public virtual OrderProduct OrderProduct { get; set; } // OrderProduct_OrderDetails

        /// <summary>
        /// Parent Product pointed by [OrderDetails].([ProductId]) (Product_OrderDetails)
        /// </summary>
        public virtual Product Product { get; set; } // Product_OrderDetails
    }

}
// </auto-generated>
