// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6



#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Store.Model.POCO_Entities
{

    // ProductBrand
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class ProductBrand
    {
        public int ProductBrandId { get; set; } // ProductBrandId (Primary key)
        public string ProductBrandName { get; set; } // ProductBrandName (length: 25)
        public string ProductBrandCountry { get; set; } // ProductBrandCountry (length: 20)

        // Reverse navigation

        /// <summary>
        /// Child Products where [Product].[ProductBrandId] point to this entity (ProductBrand_Product)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Product> Products { get; set; } // Product.ProductBrand_Product

        public ProductBrand()
        {
            Products = new System.Collections.Generic.List<Product>();
        }
    }

}
// </auto-generated>
