// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6


using Store.Model.POCO_Entities;

#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Store.Model.POCO_Entities
{

    // ProductCategory
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class ProductCategory
    {
        public int ProductCategoryId { get; set; } // ProductCategoryId (Primary key)
        public string ProductCategoryName { get; set; } // ProductCategoryName (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child ProductSubCategories where [ProductSubCategory].[ProductCategoryId] point to this entity (ProductCategory_ProductSubCategory)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ProductSubCategory> ProductSubCategories { get; set; } // ProductSubCategory.ProductCategory_ProductSubCategory

        public ProductCategory()
        {
            ProductSubCategories = new System.Collections.Generic.List<ProductSubCategory>();
        }
    }

}
// </auto-generated>
