// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Store.Data
{

    // CusomerPhone
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class CusomerPhoneConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<CusomerPhone>
    {
        public CusomerPhoneConfiguration()
            : this("dbo")
        {
        }

        public CusomerPhoneConfiguration(string schema)
        {
            ToTable("CusomerPhone", schema);
            HasKey(x => new { x.CustomerPhoneId, x.CustomerId });

            Property(x => x.CustomerId).HasColumnName(@"CustomerId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.CustomerPhoneNumber).HasColumnName(@"CustomerPhoneNumber").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(10);
            Property(x => x.CustomerPhoneId).HasColumnName(@"CustomerPhoneId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);

            // Foreign keys
            HasRequired(a => a.Customer).WithMany(b => b.CusomerPhones).HasForeignKey(c => c.CustomerId); // Customer_CustomerPhone
        }
    }

}
// </auto-generated>
