// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6

using Store.Model.POCO_Entities;

#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Store.Data
{

    // ProductBrand
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class ProductBrandConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ProductBrand>
    {
        public ProductBrandConfiguration()
            : this("dbo")
        {
        }

        public ProductBrandConfiguration(string schema)
        {
            ToTable("ProductBrand", schema);
            HasKey(x => x.ProductBrandId);

            Property(x => x.ProductBrandId).HasColumnName(@"ProductBrandId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ProductBrandName).HasColumnName(@"ProductBrandName").HasColumnType("nvarchar").IsOptional().HasMaxLength(25);
            Property(x => x.ProductBrandCountry).HasColumnName(@"ProductBrandCountry").HasColumnType("nvarchar").IsOptional().HasMaxLength(20);
        }
    }

}
// </auto-generated>
