// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6

using Store.Model.POCO_Entities;
using Store.Model.POCO_Entities;

#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Store.Data
{

    // ProductSubCategory
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class ProductSubCategoryConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ProductSubCategory>
    {
        public ProductSubCategoryConfiguration()
            : this("dbo")
        {
        }

        public ProductSubCategoryConfiguration(string schema)
        {
            ToTable("ProductSubCategory", schema);
            HasKey(x => new { x.ProductSubCategoryId, x.ProductCategoryId });

            Property(x => x.ProductSubCategoryId).HasColumnName(@"ProductSubCategoryId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ProductSubCategoryName).HasColumnName(@"ProductSubCategoryName").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.ProductCategoryId).HasColumnName(@"ProductCategoryId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);

            // Foreign keys
            HasRequired(a => a.ProductCategory).WithMany(b => b.ProductSubCategories).HasForeignKey(c => c.ProductCategoryId).WillCascadeOnDelete(false); // ProductCategory_ProductSubCategory
        }
    }

}
// </auto-generated>
