//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 08.10.2017 10:40:17
namespace Store.DomainModel.DTOs
{
    /// <summary>
    /// There are no comments for ProductSingle in the schema.
    /// </summary>
    public partial class ProductSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Product>
    {
        /// <summary>
        /// Initialize a new ProductSingle object.
        /// </summary>
        public ProductSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ProductSingle object.
        /// </summary>
        public ProductSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ProductSingle object.
        /// </summary>
        public ProductSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Product> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for Product in the schema.
    /// </summary>
    /// <KeyProperties>
    /// productId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("productId")]
    public partial class Product : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="productId">Initial value of productId.</param>
        /// <param name="productPrice">Initial value of productPrice.</param>
        /// <param name="productQuanity">Initial value of productQuanity.</param>
        /// <param name="productOrderCount">Initial value of productOrderCount.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Product CreateProduct(int productId, decimal productPrice, decimal productQuanity, int productOrderCount)
        {
            Product product = new Product();
            product.productId = productId;
            product.productPrice = productPrice;
            product.productQuanity = productQuanity;
            product.productOrderCount = productOrderCount;
            return product;
        }
        /// <summary>
        /// There are no comments for Property productId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int productId
        {
            get
            {
                return this._productId;
            }
            set
            {
                this.OnproductIdChanging(value);
                this._productId = value;
                this.OnproductIdChanged();
                this.OnPropertyChanged("productId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _productId;
        partial void OnproductIdChanging(int value);
        partial void OnproductIdChanged();
        /// <summary>
        /// There are no comments for Property productName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string productName
        {
            get
            {
                return this._productName;
            }
            set
            {
                this.OnproductNameChanging(value);
                this._productName = value;
                this.OnproductNameChanged();
                this.OnPropertyChanged("productName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _productName;
        partial void OnproductNameChanging(string value);
        partial void OnproductNameChanged();
        /// <summary>
        /// There are no comments for Property productPrice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public decimal productPrice
        {
            get
            {
                return this._productPrice;
            }
            set
            {
                this.OnproductPriceChanging(value);
                this._productPrice = value;
                this.OnproductPriceChanged();
                this.OnPropertyChanged("productPrice");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private decimal _productPrice;
        partial void OnproductPriceChanging(decimal value);
        partial void OnproductPriceChanged();
        /// <summary>
        /// There are no comments for Property productDescription in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string productDescription
        {
            get
            {
                return this._productDescription;
            }
            set
            {
                this.OnproductDescriptionChanging(value);
                this._productDescription = value;
                this.OnproductDescriptionChanged();
                this.OnPropertyChanged("productDescription");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _productDescription;
        partial void OnproductDescriptionChanging(string value);
        partial void OnproductDescriptionChanged();
        /// <summary>
        /// There are no comments for Property productQuanity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public decimal productQuanity
        {
            get
            {
                return this._productQuanity;
            }
            set
            {
                this.OnproductQuanityChanging(value);
                this._productQuanity = value;
                this.OnproductQuanityChanged();
                this.OnPropertyChanged("productQuanity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private decimal _productQuanity;
        partial void OnproductQuanityChanging(decimal value);
        partial void OnproductQuanityChanged();
        /// <summary>
        /// There are no comments for Property productCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string productCode
        {
            get
            {
                return this._productCode;
            }
            set
            {
                this.OnproductCodeChanging(value);
                this._productCode = value;
                this.OnproductCodeChanged();
                this.OnPropertyChanged("productCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _productCode;
        partial void OnproductCodeChanging(string value);
        partial void OnproductCodeChanged();
        /// <summary>
        /// There are no comments for Property productDiscount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<int> productDiscount
        {
            get
            {
                return this._productDiscount;
            }
            set
            {
                this.OnproductDiscountChanging(value);
                this._productDiscount = value;
                this.OnproductDiscountChanged();
                this.OnPropertyChanged("productDiscount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _productDiscount;
        partial void OnproductDiscountChanging(global::System.Nullable<int> value);
        partial void OnproductDiscountChanged();
        /// <summary>
        /// There are no comments for Property productBrandName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string productBrandName
        {
            get
            {
                return this._productBrandName;
            }
            set
            {
                this.OnproductBrandNameChanging(value);
                this._productBrandName = value;
                this.OnproductBrandNameChanged();
                this.OnPropertyChanged("productBrandName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _productBrandName;
        partial void OnproductBrandNameChanging(string value);
        partial void OnproductBrandNameChanged();
        /// <summary>
        /// There are no comments for Property productBrandCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string productBrandCountry
        {
            get
            {
                return this._productBrandCountry;
            }
            set
            {
                this.OnproductBrandCountryChanging(value);
                this._productBrandCountry = value;
                this.OnproductBrandCountryChanged();
                this.OnPropertyChanged("productBrandCountry");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _productBrandCountry;
        partial void OnproductBrandCountryChanging(string value);
        partial void OnproductBrandCountryChanged();
        /// <summary>
        /// There are no comments for Property productManufacturerCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string productManufacturerCountry
        {
            get
            {
                return this._productManufacturerCountry;
            }
            set
            {
                this.OnproductManufacturerCountryChanging(value);
                this._productManufacturerCountry = value;
                this.OnproductManufacturerCountryChanged();
                this.OnPropertyChanged("productManufacturerCountry");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _productManufacturerCountry;
        partial void OnproductManufacturerCountryChanging(string value);
        partial void OnproductManufacturerCountryChanged();
        /// <summary>
        /// There are no comments for Property productSubCategoryName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string productSubCategoryName
        {
            get
            {
                return this._productSubCategoryName;
            }
            set
            {
                this.OnproductSubCategoryNameChanging(value);
                this._productSubCategoryName = value;
                this.OnproductSubCategoryNameChanged();
                this.OnPropertyChanged("productSubCategoryName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _productSubCategoryName;
        partial void OnproductSubCategoryNameChanging(string value);
        partial void OnproductSubCategoryNameChanged();
        /// <summary>
        /// There are no comments for Property productCategoryName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string productCategoryName
        {
            get
            {
                return this._productCategoryName;
            }
            set
            {
                this.OnproductCategoryNameChanging(value);
                this._productCategoryName = value;
                this.OnproductCategoryNameChanged();
                this.OnPropertyChanged("productCategoryName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _productCategoryName;
        partial void OnproductCategoryNameChanging(string value);
        partial void OnproductCategoryNameChanged();
        /// <summary>
        /// There are no comments for Property productImageLargeUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string productImageLargeUrl
        {
            get
            {
                return this._productImageLargeUrl;
            }
            set
            {
                this.OnproductImageLargeUrlChanging(value);
                this._productImageLargeUrl = value;
                this.OnproductImageLargeUrlChanged();
                this.OnPropertyChanged("productImageLargeUrl");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _productImageLargeUrl;
        partial void OnproductImageLargeUrlChanging(string value);
        partial void OnproductImageLargeUrlChanged();
        /// <summary>
        /// There are no comments for Property productImageSmallUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string productImageSmallUrl
        {
            get
            {
                return this._productImageSmallUrl;
            }
            set
            {
                this.OnproductImageSmallUrlChanging(value);
                this._productImageSmallUrl = value;
                this.OnproductImageSmallUrlChanged();
                this.OnPropertyChanged("productImageSmallUrl");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _productImageSmallUrl;
        partial void OnproductImageSmallUrlChanging(string value);
        partial void OnproductImageSmallUrlChanged();
        /// <summary>
        /// There are no comments for Property productOrderCount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int productOrderCount
        {
            get
            {
                return this._productOrderCount;
            }
            set
            {
                this.OnproductOrderCountChanging(value);
                this._productOrderCount = value;
                this.OnproductOrderCountChanged();
                this.OnPropertyChanged("productOrderCount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _productOrderCount;
        partial void OnproductOrderCountChanging(int value);
        partial void OnproductOrderCountChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ProductBrandSingle in the schema.
    /// </summary>
    public partial class ProductBrandSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<ProductBrand>
    {
        /// <summary>
        /// Initialize a new ProductBrandSingle object.
        /// </summary>
        public ProductBrandSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ProductBrandSingle object.
        /// </summary>
        public ProductBrandSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ProductBrandSingle object.
        /// </summary>
        public ProductBrandSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<ProductBrand> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for ProductBrand in the schema.
    /// </summary>
    /// <KeyProperties>
    /// productBrandId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("productBrandId")]
    public partial class ProductBrand : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ProductBrand object.
        /// </summary>
        /// <param name="productBrandId">Initial value of productBrandId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static ProductBrand CreateProductBrand(int productBrandId)
        {
            ProductBrand productBrand = new ProductBrand();
            productBrand.productBrandId = productBrandId;
            return productBrand;
        }
        /// <summary>
        /// There are no comments for Property productBrandId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int productBrandId
        {
            get
            {
                return this._productBrandId;
            }
            set
            {
                this.OnproductBrandIdChanging(value);
                this._productBrandId = value;
                this.OnproductBrandIdChanged();
                this.OnPropertyChanged("productBrandId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _productBrandId;
        partial void OnproductBrandIdChanging(int value);
        partial void OnproductBrandIdChanged();
        /// <summary>
        /// There are no comments for Property productBrandName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string productBrandName
        {
            get
            {
                return this._productBrandName;
            }
            set
            {
                this.OnproductBrandNameChanging(value);
                this._productBrandName = value;
                this.OnproductBrandNameChanged();
                this.OnPropertyChanged("productBrandName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _productBrandName;
        partial void OnproductBrandNameChanging(string value);
        partial void OnproductBrandNameChanged();
        /// <summary>
        /// There are no comments for Property productBrandCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string productBrandCountry
        {
            get
            {
                return this._productBrandCountry;
            }
            set
            {
                this.OnproductBrandCountryChanging(value);
                this._productBrandCountry = value;
                this.OnproductBrandCountryChanged();
                this.OnPropertyChanged("productBrandCountry");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _productBrandCountry;
        partial void OnproductBrandCountryChanging(string value);
        partial void OnproductBrandCountryChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OrderDetailDtoSingle in the schema.
    /// </summary>
    public partial class OrderDetailDtoSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<OrderDetailDto>
    {
        /// <summary>
        /// Initialize a new OrderDetailDtoSingle object.
        /// </summary>
        public OrderDetailDtoSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new OrderDetailDtoSingle object.
        /// </summary>
        public OrderDetailDtoSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new OrderDetailDtoSingle object.
        /// </summary>
        public OrderDetailDtoSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<OrderDetailDto> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for OrderDetailDto in the schema.
    /// </summary>
    /// <KeyProperties>
    /// productId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("productId")]
    public partial class OrderDetailDto : Product
    {
        /// <summary>
        /// Create a new OrderDetailDto object.
        /// </summary>
        /// <param name="productId">Initial value of productId.</param>
        /// <param name="productPrice">Initial value of productPrice.</param>
        /// <param name="productQuanity">Initial value of productQuanity.</param>
        /// <param name="productOrderCount">Initial value of productOrderCount.</param>
        /// <param name="orderProductId">Initial value of orderProductId.</param>
        /// <param name="orderDetailsQuantity">Initial value of orderDetailsQuantity.</param>
        /// <param name="orderDetailsPrice">Initial value of orderDetailsPrice.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static OrderDetailDto CreateOrderDetailDto(int productId, 
                    decimal productPrice, 
                    decimal productQuanity, 
                    int productOrderCount, 
                    long orderProductId, 
                    decimal orderDetailsQuantity, 
                    decimal orderDetailsPrice)
        {
            OrderDetailDto orderDetailDto = new OrderDetailDto();
            orderDetailDto.productId = productId;
            orderDetailDto.productPrice = productPrice;
            orderDetailDto.productQuanity = productQuanity;
            orderDetailDto.productOrderCount = productOrderCount;
            orderDetailDto.orderProductId = orderProductId;
            orderDetailDto.orderDetailsQuantity = orderDetailsQuantity;
            orderDetailDto.orderDetailsPrice = orderDetailsPrice;
            return orderDetailDto;
        }
        /// <summary>
        /// There are no comments for Property orderProductId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public long orderProductId
        {
            get
            {
                return this._orderProductId;
            }
            set
            {
                this.OnorderProductIdChanging(value);
                this._orderProductId = value;
                this.OnorderProductIdChanged();
                this.OnPropertyChanged("orderProductId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private long _orderProductId;
        partial void OnorderProductIdChanging(long value);
        partial void OnorderProductIdChanged();
        /// <summary>
        /// There are no comments for Property orderDetailsQuantity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public decimal orderDetailsQuantity
        {
            get
            {
                return this._orderDetailsQuantity;
            }
            set
            {
                this.OnorderDetailsQuantityChanging(value);
                this._orderDetailsQuantity = value;
                this.OnorderDetailsQuantityChanged();
                this.OnPropertyChanged("orderDetailsQuantity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private decimal _orderDetailsQuantity;
        partial void OnorderDetailsQuantityChanging(decimal value);
        partial void OnorderDetailsQuantityChanged();
        /// <summary>
        /// There are no comments for Property orderDetailsPrice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public decimal orderDetailsPrice
        {
            get
            {
                return this._orderDetailsPrice;
            }
            set
            {
                this.OnorderDetailsPriceChanging(value);
                this._orderDetailsPrice = value;
                this.OnorderDetailsPriceChanged();
                this.OnPropertyChanged("orderDetailsPrice");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private decimal _orderDetailsPrice;
        partial void OnorderDetailsPriceChanging(decimal value);
        partial void OnorderDetailsPriceChanged();
        /// <summary>
        /// There are no comments for Property orderDetailsDiscountPrice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<decimal> orderDetailsDiscountPrice
        {
            get
            {
                return this._orderDetailsDiscountPrice;
            }
            set
            {
                this.OnorderDetailsDiscountPriceChanging(value);
                this._orderDetailsDiscountPrice = value;
                this.OnorderDetailsDiscountPriceChanged();
                this.OnPropertyChanged("orderDetailsDiscountPrice");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<decimal> _orderDetailsDiscountPrice;
        partial void OnorderDetailsDiscountPriceChanging(global::System.Nullable<decimal> value);
        partial void OnorderDetailsDiscountPriceChanged();
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::Store.DomainModel.DTOs.Product as global::Store.DomainModel.DTOs.ProductSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Store.DomainModel.DTOs.ProductSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Store.DomainModel.DTOs.Product> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Store.DomainModel.DTOs.ProductSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Store.DomainModel.DTOs.Product as global::Store.DomainModel.DTOs.ProductSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="productId">The value of productId</param>
        public static global::Store.DomainModel.DTOs.ProductSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Store.DomainModel.DTOs.Product> source,
            int productId)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "productId", productId }
            };
            return new global::Store.DomainModel.DTOs.ProductSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Store.DomainModel.DTOs.ProductBrand as global::Store.DomainModel.DTOs.ProductBrandSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Store.DomainModel.DTOs.ProductBrandSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Store.DomainModel.DTOs.ProductBrand> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Store.DomainModel.DTOs.ProductBrandSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Store.DomainModel.DTOs.ProductBrand as global::Store.DomainModel.DTOs.ProductBrandSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="productBrandId">The value of productBrandId</param>
        public static global::Store.DomainModel.DTOs.ProductBrandSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Store.DomainModel.DTOs.ProductBrand> source,
            int productBrandId)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "productBrandId", productBrandId }
            };
            return new global::Store.DomainModel.DTOs.ProductBrandSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Store.DomainModel.DTOs.OrderDetailDto as global::Store.DomainModel.DTOs.OrderDetailDtoSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Store.DomainModel.DTOs.OrderDetailDtoSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Store.DomainModel.DTOs.OrderDetailDto> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Store.DomainModel.DTOs.OrderDetailDtoSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Store.DomainModel.DTOs.OrderDetailDto as global::Store.DomainModel.DTOs.OrderDetailDtoSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="productId">The value of productId</param>
        public static global::Store.DomainModel.DTOs.OrderDetailDtoSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Store.DomainModel.DTOs.OrderDetailDto> source,
            int productId)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "productId", productId }
            };
            return new global::Store.DomainModel.DTOs.OrderDetailDtoSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Cast an entity of type global::Store.DomainModel.DTOs.Product to its derived type global::Store.DomainModel.DTOs.OrderDetailDto
        /// </summary>
        /// <param name="source">source entity</param>
        public static global::Store.DomainModel.DTOs.OrderDetailDtoSingle CastToOrderDetailDto(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::Store.DomainModel.DTOs.Product> source)
        {
            global::Microsoft.OData.Client.DataServiceQuerySingle<global::Store.DomainModel.DTOs.OrderDetailDto> query = source.CastTo<global::Store.DomainModel.DTOs.OrderDetailDto>();
            return new global::Store.DomainModel.DTOs.OrderDetailDtoSingle(source.Context, query.GetPath(null));
        }
    }
}
namespace Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            return clientType.FullName;
        }
        /// <summary>
        /// There are no comments for Products in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Store.DomainModel.DTOs.Product> Products
        {
            get
            {
                if ((this._Products == null))
                {
                    this._Products = base.CreateQuery<global::Store.DomainModel.DTOs.Product>("Products");
                }
                return this._Products;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Store.DomainModel.DTOs.Product> _Products;
        /// <summary>
        /// There are no comments for ProductBrands in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Store.DomainModel.DTOs.ProductBrand> ProductBrands
        {
            get
            {
                if ((this._ProductBrands == null))
                {
                    this._ProductBrands = base.CreateQuery<global::Store.DomainModel.DTOs.ProductBrand>("ProductBrands");
                }
                return this._ProductBrands;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Store.DomainModel.DTOs.ProductBrand> _ProductBrands;
        /// <summary>
        /// There are no comments for Products in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToProducts(global::Store.DomainModel.DTOs.Product product)
        {
            base.AddObject("Products", product);
        }
        /// <summary>
        /// There are no comments for ProductBrands in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToProductBrands(global::Store.DomainModel.DTOs.ProductBrand productBrand)
        {
            base.AddObject("ProductBrands", productBrand);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""Store.DomainModel.DTOs"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""Product"">
        <Key>
          <PropertyRef Name=""productId"" />
        </Key>
        <Property Name=""productId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""productName"" Type=""Edm.String"" />
        <Property Name=""productPrice"" Type=""Edm.Decimal"" Nullable=""false"" />
        <Property Name=""productDescription"" Type=""Edm.String"" />
        <Property Name=""productQuanity"" Type=""Edm.Decimal"" Nullable=""false"" />
        <Property Name=""productCode"" Type=""Edm.String"" />
        <Property Name=""productDiscount"" Type=""Edm.Int32"" />
        <Property Name=""productBrandName"" Type=""Edm.String"" />
        <Property Name=""productBrandCountry"" Type=""Edm.String"" />
        <Property Name=""productManufacturerCountry"" Type=""Edm.String"" />
        <Property Name=""productSubCategoryName"" Type=""Edm.String"" />
        <Property Name=""productCategoryName"" Type=""Edm.String"" />
        <Property Name=""productImageLargeUrl"" Type=""Edm.String"" />
        <Property Name=""productImageSmallUrl"" Type=""Edm.String"" />
        <Property Name=""productOrderCount"" Type=""Edm.Int32"" Nullable=""false"" />
      </EntityType>
      <EntityType Name=""ProductBrand"">
        <Key>
          <PropertyRef Name=""productBrandId"" />
        </Key>
        <Property Name=""productBrandId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""productBrandName"" Type=""Edm.String"" />
        <Property Name=""productBrandCountry"" Type=""Edm.String"" />
      </EntityType>
      <EntityType Name=""OrderDetailDto"" BaseType=""Store.DomainModel.DTOs.Product"">
        <Property Name=""orderProductId"" Type=""Edm.Int64"" Nullable=""false"" />
        <Property Name=""orderDetailsQuantity"" Type=""Edm.Decimal"" Nullable=""false"" />
        <Property Name=""orderDetailsPrice"" Type=""Edm.Decimal"" Nullable=""false"" />
        <Property Name=""orderDetailsDiscountPrice"" Type=""Edm.Decimal"" />
      </EntityType>
    </Schema>
    <Schema Namespace=""Default"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityContainer Name=""Container"">
        <EntitySet Name=""Products"" EntityType=""Store.DomainModel.DTOs.Product"" />
        <EntitySet Name=""ProductBrands"" EntityType=""Store.DomainModel.DTOs.ProductBrand"" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
}
