// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Store.Data
{

    // ProductSubCategory
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class ProductSubCategory
    {
        public int ProductSubCategoryId { get; set; } // ProductSubCategoryId (Primary key)
        public string ProductSubCategoryName { get; set; } // ProductSubCategoryName (length: 50)
        public int ProductCategoryId { get; set; } // ProductCategoryId (Primary key)

        // Reverse navigation

        /// <summary>
        /// Child Products where [Product].([ProductCategoryId], [ProductSubCategoryId]) point to this entity (ProductSubCategory_Product)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Product> Products { get; set; } // Product.ProductSubCategory_Product

        // Foreign keys

        /// <summary>
        /// Parent ProductCategory pointed by [ProductSubCategory].([ProductCategoryId]) (ProductCategory_ProductSubCategory)
        /// </summary>
        public virtual ProductCategory ProductCategory { get; set; } // ProductCategory_ProductSubCategory

        public ProductSubCategory()
        {
            Products = new System.Collections.Generic.List<Product>();
        }
    }

}
// </auto-generated>
