// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Store.Data
{

    // ProductManufacturer
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class ProductManufacturer
    {
        public int ProductManufacturerId { get; set; } // ProductManufacturerId (Primary key)
        public string ProductManufacturerCountry { get; set; } // ProductManufacturerCountry (length: 20)

        // Reverse navigation

        /// <summary>
        /// Child Products where [Product].[ProductManufacturerId] point to this entity (ProductManufacterer_Product)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Product> Products { get; set; } // Product.ProductManufacterer_Product

        public ProductManufacturer()
        {
            Products = new System.Collections.Generic.List<Product>();
        }
    }

}
// </auto-generated>
