// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6

using System.Data.Entity;
using System.Data.Entity.ModelConfiguration.Conventions;
using Microsoft.AspNet.Identity.EntityFramework;
using Store.Data.Context;
using Store.Data.EntityTypeConfigurations;
using Store.Model.IdentityEntities;
using Store.Model.POCO_Entities;

#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Store.Data
{
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class StoreDbContext : IdentityDbContext<ApplicationUser>, IStoreDbContext
    {
        public System.Data.Entity.DbSet<CustomerPhone> CusomerPhones { get; set; } // CusomerPhone
        public System.Data.Entity.DbSet<Customer> Customers { get; set; } // Customer
        public System.Data.Entity.DbSet<OrderDetail> OrderDetails { get; set; } // OrderDetails
        public System.Data.Entity.DbSet<OrderProduct> OrderProducts { get; set; } // OrderProduct
        public System.Data.Entity.DbSet<Product> Products { get; set; } // Product
        public System.Data.Entity.DbSet<ProductBrand> ProductBrands { get; set; } // ProductBrand
        public System.Data.Entity.DbSet<ProductCategory> ProductCategories { get; set; } // ProductCategory
        public System.Data.Entity.DbSet<ProductManufacturer> ProductManufacturers { get; set; } // ProductManufacturer
        public System.Data.Entity.DbSet<ProductSubCategory> ProductSubCategories { get; set; } // ProductSubCategory
        public System.Data.Entity.DbSet<Cart> Carts { get; set; } // Cart
        public System.Data.Entity.DbSet<CartItem> CartItems { get; set; } // CartItem

        static StoreDbContext()
        {
            Database.SetInitializer<StoreDbContext>(new StoreDbInitializer());
        }

        public StoreDbContext()
            : base("Name=StoreConnection", throwIfV1Schema: false)
        {
        }

        public StoreDbContext(string connectionString)
            : base(connectionString, throwIfV1Schema: false)
        {
        }

        public StoreDbContext(string connectionString, System.Data.Entity.Infrastructure.DbCompiledModel model)
            : base(connectionString, model)
        {
        }

        public StoreDbContext(System.Data.Common.DbConnection existingConnection, bool contextOwnsConnection)
            : base(existingConnection, contextOwnsConnection)
        {
        }

        public StoreDbContext(System.Data.Common.DbConnection existingConnection, System.Data.Entity.Infrastructure.DbCompiledModel model, bool contextOwnsConnection)
            : base(existingConnection, model, contextOwnsConnection)
        {
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }

        public bool IsSqlParameterNull(System.Data.SqlClient.SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as System.Data.SqlTypes.INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == System.DBNull.Value);
        }

        public static StoreDbContext Create()
        {
            return new StoreDbContext();
        }

        protected override void OnModelCreating(System.Data.Entity.DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();

            // one-to-zero or one relationship between ApplicationUser and Customer
            // UserId column in Customers table will be foreign key
            modelBuilder.Entity<ApplicationUser>()
                .HasOptional(m => m.Customer)
                .WithRequired(m => m.ApplicationUser)
                .Map(p => p.MapKey("UserId"));

            modelBuilder.Configurations.Add(new CusomerPhoneConfiguration());
            modelBuilder.Configurations.Add(new CustomerConfiguration());
            modelBuilder.Configurations.Add(new OrderDetailConfiguration());
            modelBuilder.Configurations.Add(new OrderProductConfiguration());
            modelBuilder.Configurations.Add(new ProductConfiguration());
            modelBuilder.Configurations.Add(new ProductBrandConfiguration());
            modelBuilder.Configurations.Add(new ProductCategoryConfiguration());
            modelBuilder.Configurations.Add(new ProductManufacturerConfiguration());
            modelBuilder.Configurations.Add(new ProductSubCategoryConfiguration());
            modelBuilder.Configurations.Add(new CartConfigurations());
            modelBuilder.Configurations.Add(new CartItemConfigurations());
        }

        public static System.Data.Entity.DbModelBuilder CreateModel(System.Data.Entity.DbModelBuilder modelBuilder, string schema)
        {
            modelBuilder.Configurations.Add(new CusomerPhoneConfiguration(schema));
            modelBuilder.Configurations.Add(new CustomerConfiguration(schema));
            modelBuilder.Configurations.Add(new OrderDetailConfiguration(schema));
            modelBuilder.Configurations.Add(new OrderProductConfiguration(schema));
            modelBuilder.Configurations.Add(new ProductConfiguration(schema));
            modelBuilder.Configurations.Add(new ProductBrandConfiguration(schema));
            modelBuilder.Configurations.Add(new ProductCategoryConfiguration(schema));
            modelBuilder.Configurations.Add(new ProductManufacturerConfiguration(schema));
            modelBuilder.Configurations.Add(new ProductSubCategoryConfiguration(schema));
            modelBuilder.Configurations.Add(new CartConfigurations());
            modelBuilder.Configurations.Add(new CartItemConfigurations());

            return modelBuilder;
        }
    }
}
// </auto-generated>
