//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.Web.Mvc.Client.ImageServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ImageServiceReference.IImageService")]
    public interface IImageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/GetProductImageLarge", ReplyAction="http://tempuri.org/IImageService/GetProductImageLargeResponse")]
        System.IO.Stream GetProductImageLarge(string productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/GetProductImageLarge", ReplyAction="http://tempuri.org/IImageService/GetProductImageLargeResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetProductImageLargeAsync(string productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/GetProductImageSmall", ReplyAction="http://tempuri.org/IImageService/GetProductImageSmallResponse")]
        System.IO.Stream GetProductImageSmall(string productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/GetProductImageSmall", ReplyAction="http://tempuri.org/IImageService/GetProductImageSmallResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetProductImageSmallAsync(string productId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IImageServiceChannel : Store.Web.Mvc.Client.ImageServiceReference.IImageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImageServiceClient : System.ServiceModel.ClientBase<Store.Web.Mvc.Client.ImageServiceReference.IImageService>, Store.Web.Mvc.Client.ImageServiceReference.IImageService {
        
        public ImageServiceClient() {
        }
        
        public ImageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.IO.Stream GetProductImageLarge(string productId) {
            return base.Channel.GetProductImageLarge(productId);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetProductImageLargeAsync(string productId) {
            return base.Channel.GetProductImageLargeAsync(productId);
        }
        
        public System.IO.Stream GetProductImageSmall(string productId) {
            return base.Channel.GetProductImageSmall(productId);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetProductImageSmallAsync(string productId) {
            return base.Channel.GetProductImageSmallAsync(productId);
        }
    }
}
